// GENERATED by scripts/gen-services.ts from the public service catalog — do not edit by hand.
// Availability and prices are decided by the API at run time: use `mv.services()` (GET /v1/services).

export interface ServiceInfo {
  code: string;
  name: string;
  /** Platform name, used descriptively only (no affiliation). */
  platform: string;
  family: string;
  /** phone → checks `numbers`; email → checks `emails`. */
  inputType: "phone" | "email";
  /** boolean = registered yes/no (+ optional attributes); attributes = data (e.g. carrier). */
  resultKind: "boolean" | "attributes";
  /** Usable in real time (`lookup`); otherwise bulk jobs only. */
  realtime: boolean;
  beta: boolean;
  attributes: readonly string[];
  /** ISO alpha-2 countries; empty = all. */
  countries: readonly string[];
}

export const SERVICE_CATALOG = [
  {
    "code": "whatsapp.registered",
    "name": "WhatsApp registration",
    "platform": "WhatsApp",
    "family": "messaging",
    "inputType": "phone",
    "resultKind": "boolean",
    "realtime": true,
    "beta": false,
    "attributes": [],
    "countries": []
  },
  {
    "code": "whatsapp.business",
    "name": "WhatsApp Business account",
    "platform": "WhatsApp",
    "family": "messaging",
    "inputType": "phone",
    "resultKind": "boolean",
    "realtime": true,
    "beta": false,
    "attributes": [
      "business"
    ],
    "countries": []
  },
  {
    "code": "telegram.registered",
    "name": "Telegram registration",
    "platform": "Telegram",
    "family": "messaging",
    "inputType": "phone",
    "resultKind": "boolean",
    "realtime": true,
    "beta": false,
    "attributes": [],
    "countries": []
  },
  {
    "code": "viber.registered",
    "name": "Viber registration",
    "platform": "Viber",
    "family": "messaging",
    "inputType": "phone",
    "resultKind": "boolean",
    "realtime": true,
    "beta": false,
    "attributes": [],
    "countries": []
  },
  {
    "code": "signal.registered",
    "name": "Signal registration",
    "platform": "Signal",
    "family": "messaging",
    "inputType": "phone",
    "resultKind": "boolean",
    "realtime": false,
    "beta": false,
    "attributes": [],
    "countries": []
  },
  {
    "code": "imessage.registered",
    "name": "iMessage registration",
    "platform": "iMessage",
    "family": "messaging",
    "inputType": "phone",
    "resultKind": "boolean",
    "realtime": false,
    "beta": false,
    "attributes": [],
    "countries": []
  },
  {
    "code": "rcs.registered",
    "name": "RCS capability",
    "platform": "RCS",
    "family": "messaging",
    "inputType": "phone",
    "resultKind": "boolean",
    "realtime": false,
    "beta": false,
    "attributes": [
      "device_os"
    ],
    "countries": []
  },
  {
    "code": "line.registered",
    "name": "LINE registration",
    "platform": "LINE",
    "family": "messaging",
    "inputType": "phone",
    "resultKind": "boolean",
    "realtime": false,
    "beta": false,
    "attributes": [],
    "countries": []
  },
  {
    "code": "zalo.registered",
    "name": "Zalo registration",
    "platform": "Zalo",
    "family": "messaging",
    "inputType": "phone",
    "resultKind": "boolean",
    "realtime": true,
    "beta": false,
    "attributes": [],
    "countries": []
  },
  {
    "code": "botim.registered",
    "name": "Botim registration",
    "platform": "Botim",
    "family": "messaging",
    "inputType": "phone",
    "resultKind": "boolean",
    "realtime": false,
    "beta": false,
    "attributes": [],
    "countries": []
  },
  {
    "code": "max.registered",
    "name": "MAX registration",
    "platform": "MAX",
    "family": "messaging",
    "inputType": "phone",
    "resultKind": "boolean",
    "realtime": false,
    "beta": false,
    "attributes": [],
    "countries": []
  },
  {
    "code": "messenger.registered",
    "name": "Messenger registration",
    "platform": "Facebook Messenger",
    "family": "messaging",
    "inputType": "phone",
    "resultKind": "boolean",
    "realtime": false,
    "beta": false,
    "attributes": [],
    "countries": []
  },
  {
    "code": "facebook.registered",
    "name": "Facebook registration",
    "platform": "Facebook",
    "family": "social",
    "inputType": "phone",
    "resultKind": "boolean",
    "realtime": true,
    "beta": false,
    "attributes": [],
    "countries": []
  },
  {
    "code": "instagram.registered",
    "name": "Instagram registration",
    "platform": "Instagram",
    "family": "social",
    "inputType": "phone",
    "resultKind": "boolean",
    "realtime": true,
    "beta": false,
    "attributes": [],
    "countries": []
  },
  {
    "code": "threads.registered",
    "name": "Threads registration",
    "platform": "Threads",
    "family": "social",
    "inputType": "phone",
    "resultKind": "boolean",
    "realtime": true,
    "beta": false,
    "attributes": [],
    "countries": []
  },
  {
    "code": "x.registered",
    "name": "X (Twitter) registration",
    "platform": "X (Twitter)",
    "family": "social",
    "inputType": "phone",
    "resultKind": "boolean",
    "realtime": true,
    "beta": false,
    "attributes": [],
    "countries": []
  },
  {
    "code": "tiktok.registered",
    "name": "TikTok registration",
    "platform": "TikTok",
    "family": "social",
    "inputType": "phone",
    "resultKind": "boolean",
    "realtime": false,
    "beta": false,
    "attributes": [],
    "countries": []
  },
  {
    "code": "snapchat.registered",
    "name": "Snapchat registration",
    "platform": "Snapchat",
    "family": "social",
    "inputType": "phone",
    "resultKind": "boolean",
    "realtime": false,
    "beta": false,
    "attributes": [],
    "countries": []
  },
  {
    "code": "linkedin.registered",
    "name": "LinkedIn registration",
    "platform": "LinkedIn",
    "family": "social",
    "inputType": "phone",
    "resultKind": "boolean",
    "realtime": false,
    "beta": false,
    "attributes": [],
    "countries": [
      "US",
      "IN"
    ]
  },
  {
    "code": "apple.registered",
    "name": "Apple ID registration",
    "platform": "Apple",
    "family": "apps",
    "inputType": "phone",
    "resultKind": "boolean",
    "realtime": true,
    "beta": false,
    "attributes": [],
    "countries": []
  },
  {
    "code": "amazon.registered",
    "name": "Amazon registration",
    "platform": "Amazon",
    "family": "apps",
    "inputType": "phone",
    "resultKind": "boolean",
    "realtime": true,
    "beta": false,
    "attributes": [],
    "countries": []
  },
  {
    "code": "microsoft.registered",
    "name": "Microsoft account registration",
    "platform": "Microsoft",
    "family": "apps",
    "inputType": "phone",
    "resultKind": "boolean",
    "realtime": true,
    "beta": false,
    "attributes": [],
    "countries": []
  },
  {
    "code": "netflix.registered",
    "name": "Netflix registration",
    "platform": "Netflix",
    "family": "apps",
    "inputType": "phone",
    "resultKind": "boolean",
    "realtime": true,
    "beta": false,
    "attributes": [],
    "countries": []
  },
  {
    "code": "network.carrier",
    "name": "Carrier lookup",
    "platform": "Mobile network",
    "family": "network",
    "inputType": "phone",
    "resultKind": "attributes",
    "realtime": true,
    "beta": true,
    "attributes": [
      "line_type",
      "carrier",
      "original_carrier",
      "country"
    ],
    "countries": []
  },
  {
    "code": "network.carrier_us",
    "name": "US/CA carrier lookup (premium)",
    "platform": "Mobile network",
    "family": "network",
    "inputType": "phone",
    "resultKind": "attributes",
    "realtime": false,
    "beta": false,
    "attributes": [
      "line_type",
      "carrier"
    ],
    "countries": [
      "US",
      "CA"
    ]
  },
  {
    "code": "number.spam",
    "name": "Spam reputation",
    "platform": "Spam reputation",
    "family": "network",
    "inputType": "phone",
    "resultKind": "attributes",
    "realtime": true,
    "beta": false,
    "attributes": [
      "risk_level",
      "risk_score",
      "reason_regulator",
      "reason_government",
      "reason_community",
      "reason_unassigned",
      "voip_range",
      "top_category",
      "first_seen",
      "last_seen",
      "sources",
      "premium_rate",
      "personal_number"
    ],
    "countries": []
  },
  {
    "code": "number.hlr",
    "name": "Live network status (HLR)",
    "platform": "Mobile network",
    "family": "network",
    "inputType": "phone",
    "resultKind": "attributes",
    "realtime": true,
    "beta": false,
    "attributes": [
      "status",
      "ported",
      "roaming",
      "network",
      "mcc_mnc",
      "country"
    ],
    "countries": []
  },
  {
    "code": "number.mnp",
    "name": "Number portability (MNP)",
    "platform": "Mobile network",
    "family": "network",
    "inputType": "phone",
    "resultKind": "attributes",
    "realtime": true,
    "beta": false,
    "attributes": [
      "porting",
      "mcc_mnc",
      "country"
    ],
    "countries": []
  },
  {
    "code": "email.valid",
    "name": "E-mail mailbox validation",
    "platform": "E-mail",
    "family": "email",
    "inputType": "email",
    "resultKind": "boolean",
    "realtime": true,
    "beta": false,
    "attributes": [],
    "countries": []
  },
  {
    "code": "gmail.email",
    "name": "Gmail account",
    "platform": "Gmail",
    "family": "email",
    "inputType": "email",
    "resultKind": "boolean",
    "realtime": false,
    "beta": false,
    "attributes": [],
    "countries": []
  },
  {
    "code": "outlook.email",
    "name": "Outlook account",
    "platform": "Outlook",
    "family": "email",
    "inputType": "email",
    "resultKind": "boolean",
    "realtime": false,
    "beta": false,
    "attributes": [],
    "countries": []
  },
  {
    "code": "yahoo.email",
    "name": "Yahoo account",
    "platform": "Yahoo",
    "family": "email",
    "inputType": "email",
    "resultKind": "boolean",
    "realtime": false,
    "beta": false,
    "attributes": [],
    "countries": []
  },
  {
    "code": "yandex.email",
    "name": "Yandex account",
    "platform": "Yandex",
    "family": "email",
    "inputType": "email",
    "resultKind": "boolean",
    "realtime": false,
    "beta": false,
    "attributes": [],
    "countries": []
  },
  {
    "code": "mailru.email",
    "name": "Mail.ru account",
    "platform": "Mail.ru",
    "family": "email",
    "inputType": "email",
    "resultKind": "boolean",
    "realtime": false,
    "beta": false,
    "attributes": [],
    "countries": []
  },
  {
    "code": "apple.email",
    "name": "Apple ID by e-mail",
    "platform": "Apple",
    "family": "email",
    "inputType": "email",
    "resultKind": "boolean",
    "realtime": true,
    "beta": false,
    "attributes": [],
    "countries": []
  },
  {
    "code": "amazon.email",
    "name": "Amazon by e-mail",
    "platform": "Amazon",
    "family": "email",
    "inputType": "email",
    "resultKind": "boolean",
    "realtime": true,
    "beta": false,
    "attributes": [],
    "countries": []
  },
  {
    "code": "facebook.email",
    "name": "Facebook by e-mail",
    "platform": "Facebook",
    "family": "email",
    "inputType": "email",
    "resultKind": "boolean",
    "realtime": true,
    "beta": false,
    "attributes": [],
    "countries": []
  },
  {
    "code": "instagram.email",
    "name": "Instagram by e-mail",
    "platform": "Instagram",
    "family": "email",
    "inputType": "email",
    "resultKind": "boolean",
    "realtime": true,
    "beta": false,
    "attributes": [],
    "countries": []
  },
  {
    "code": "netflix.email",
    "name": "Netflix by e-mail",
    "platform": "Netflix",
    "family": "email",
    "inputType": "email",
    "resultKind": "boolean",
    "realtime": true,
    "beta": false,
    "attributes": [],
    "countries": []
  },
  {
    "code": "spotify.email",
    "name": "Spotify by e-mail",
    "platform": "Spotify",
    "family": "email",
    "inputType": "email",
    "resultKind": "boolean",
    "realtime": true,
    "beta": false,
    "attributes": [],
    "countries": []
  },
  {
    "code": "linkedin.email",
    "name": "LinkedIn by e-mail",
    "platform": "LinkedIn",
    "family": "email",
    "inputType": "email",
    "resultKind": "boolean",
    "realtime": false,
    "beta": false,
    "attributes": [],
    "countries": []
  },
  {
    "code": "x.email",
    "name": "X (Twitter) by e-mail",
    "platform": "X (Twitter)",
    "family": "email",
    "inputType": "email",
    "resultKind": "boolean",
    "realtime": false,
    "beta": false,
    "attributes": [],
    "countries": []
  }
] as const satisfies readonly ServiceInfo[];

/** Short aliases accepted in `checks`. */
export const SERVICE_ALIASES = {
  "whatsapp": "whatsapp.registered",
  "telegram": "telegram.registered",
  "viber": "viber.registered",
  "signal": "signal.registered",
  "imessage": "imessage.registered",
  "rcs": "rcs.registered",
  "line": "line.registered",
  "zalo": "zalo.registered",
  "botim": "botim.registered",
  "max": "max.registered",
  "messenger": "messenger.registered",
  "facebook": "facebook.registered",
  "instagram": "instagram.registered",
  "threads": "threads.registered",
  "x": "x.registered",
  "twitter": "x.registered",
  "tiktok": "tiktok.registered",
  "snapchat": "snapchat.registered",
  "linkedin": "linkedin.registered",
  "apple": "apple.registered",
  "amazon": "amazon.registered",
  "microsoft": "microsoft.registered",
  "netflix": "netflix.registered",
  "carrier": "network.carrier",
  "spam": "number.spam",
  "hlr": "number.hlr",
  "mnp": "number.mnp",
  "porting": "number.mnp",
  "email": "email.valid",
  "gmail": "gmail.email",
  "outlook": "outlook.email",
  "yahoo": "yahoo.email",
  "yandex": "yandex.email",
  "mailru": "mailru.email",
  "apple.email": "apple.email"
} as const;

/** Service codes known when this SDK was built. */
export type KnownServiceCode = (typeof SERVICE_CATALOG)[number]["code"];
/** Any service code (open union: the API may offer codes newer than this SDK). */
export type ServiceCode = KnownServiceCode | (string & {});
export type ServiceAlias = keyof typeof SERVICE_ALIASES;
/** What `checks` accepts: a service code or an alias. */
export type CheckInput = ServiceCode | ServiceAlias;
